language: php

php:
  - 7.4

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.testing .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test; USE test';
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
