language: php

php:
  - '7.0'
  - '7.4'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test; USE test';

install:
  - travis_retry composer install
  - vendor/bin/phpunit

services:
  - mysql
